# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "Vibe Ventures"

# This page should be the root of your website. It's important.
page = "https://www.notion.so/persistventure/Vibe-Ventures-7c75299befd04fdeb9d1b276931a3ad8"
